import type {
    Article
} from "../models/Article";


export const articles: Article[] = [

    {
        id: "visual-introduction-modular-curves",

        title:
            "A visual introduction to modular curves",

        author:
            "Elena Ruiz",

        publicationDate:
            "Sep 10, 2026",

        readingTime:
            24,

        status:
            "published",

        categories: [
            "Geometry",
            "Number theory"
        ],

        abstract:
            `
                We present an interactive and visual
                introduction to modular curves,
                connecting abstract theory with
                computational exploration and
                geometric intuition.
            `,

        imagePath:
            "/articles/modular-curves.png"
    },

    {
        id: "maione-sequence",

        title:
            "The Maione sequence and uniform distribution",

        author:
            "Marco Bellini",

        publicationDate:
            "Sep 5, 2026",

        readingTime:
            18,

        status:
            "preprint",

        categories: [
            "Number theory",
            "Dynamics"
        ],

        abstract:
            `
                An experimental analysis of the
                distribution generated by the Maione
                sequence and its relationship with
                modular trajectories.
            `,

        imagePath:
            "/articles/maione-sequence.png"
    },

    {
        id: "riemann-zeta-patterns",

        title:
            "Visual patterns in the Riemann zeta function",

        author:
            "Kai Nakamura",

        publicationDate:
            "Aug 28, 2026",

        readingTime:
            31,

        status:
            "published",

        categories: [
            "Complex analysis",
            "Visualization"
        ],

        abstract:
            `
                A visual study of complex values,
                critical lines and emerging patterns
                inside the Riemann zeta function.
            `,

        imagePath:
            "/articles/riemann-zeta.png"
    },

    {
        id: "knot-invariants",

        title:
            "Knot invariants from computational exploration",

        author:
            "Amara Chen",

        publicationDate:
            "Aug 20, 2026",

        readingTime:
            27,

        status:
            "preprint",

        categories: [
            "Topology",
            "Knot theory"
        ],

        abstract:
            `
                Computational experiments reveal
                structural relationships between knot
                representations and their invariants.
            `,

        imagePath:
            "/articles/knot-invariants.png"
    },

    {
        id: "complex-fractal-gallery",

        title:
            "A gallery of fractals in the complex plane",

        author:
            "Sophie Laurent",

        publicationDate:
            "Aug 11, 2026",

        readingTime:
            16,

        status:
            "published",

        categories: [
            "Dynamics",
            "Visualization"
        ],

        abstract:
            `
                An illustrated exploration of fractal
                families produced by transformations
                over the complex plane.
            `,

        imagePath:
            "/articles/complex-fractals.png"
    },

    {
        id: "category-theory-visual",

        title:
            "Category theory for visual thinkers",

        author:
            "Daniel Park",

        publicationDate:
            "Aug 2, 2026",

        readingTime:
            22,

        status:
            "draft",

        categories: [
            "Category theory"
        ],

        abstract:
            `
                A visual introduction to objects,
                morphisms and compositional structures
                for readers who think geometrically.
            `,

        imagePath:
            "/articles/category-theory.png"
    }

];